=== ChristianMeisenbichler/SAXS/SAXS/DataConsolidationConf.json
{
	"type": "object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"properties": 
	{
		"TimeOffset": 
		{
			"type": "number",
			"default": "0",
			"units": "Seconds",
			"description": "If offset is not found otherwise, use this as offset  for all log data"
		},

		"LogDataTables": 
		{
			"description": "Define log files to consolidate with image data. If more then one defined, they will be joined and missing values will be interpolated.",
			"type": "array",
			"required": false,
			"items": 
			{
				"description": "One log data table is one set of logfiles with identical collumn definitions.",
				"type": "object",
				"properties": 
				{
					"TimeEpoc": 
					{
						"required": true,
						"type": "string",
						"enum": 
						[
							"Mac",
							"Unix"
						]
					},

					"TimeOffset": 
					{
						"type": "number",
						"default": "0",
						"units": "Seconds",
						"description": "If offset is not found otherwise, use this as offset."
					},

					"FirstImageCorrelation": 
					{
						"description": "Find offset for all log data by correlating first image with first entry of this table. ",
						"type": "boolean",
						"default": false
					},

					"Name": 
					{
						"description": "Name field to be used as prefix in the joined collumn names.",
						"required": true,
						"type": "string",
						"default": "log"
					},

					"Files": 
					{
						"required": false,
						"description": "One log table may be one file, or a list of files to be concatenated.",
						"type": "array",
						"minitems": 1,
						"items": 
						{
							"type": "object",
							"properties": 
							{
								"Path": 
								{
									"type": "array",
									"items": 
									{
										"type": "string",
										"default": ".",
										"appinfo": 
										{
											"editor": "RemoteFile"
										}
									}
								}
							}
						}
					}
				}
			}
		},

		"OutputFormats": 
		{
			"description": "List of outputformats to write the consolidated log or the consolidated 'hdf' file.",
			"type": "object",
			"properties": 
			{
				"csv": 
				{
					"type": "boolean",
					"default": false
				},

				"hdf": 
				{
					"type": "boolean",
					"default": false
				},

				"exel": 
				{
					"type": "boolean",
					"default": false
				},

				"json": 
				{
					"type": "boolean",
					"default": false
				}
			}
		},

		"OutputFileBaseName": 
		{
			"type": "string",
			"default": "merged"
		},

		"HDFOptions": 
		{
			"description": "Options only relevant to hdf export.",
			"type": "object",
			"properties": 
			{
				"IncludeCHI": 
				{
					"description": "Whether to include the .chi files as strings.",
					"type": "boolean",
					"default": true
				},

				"IncludetTIF": 
				{
					"description": "Whether to include the images as integer array.",
					"type": "boolean",
					"default": true
				}
			}
		}
	}
}

=== ChristianMeisenbichler/SAXS/SAXS/consolconftemplate.json
{
  "TimeOffset": 0.0, 
  "LogDataTables": [
    {
      "TimeEpoch": "Mac", 
      "TimeOffset": 0.0, 
      "FirstImageCorrelation": false, 
      "ZeroImageCorrelation": true, 
      "Name": "Peak", 
      "Files": [
        {
          "Path": [
            "140721_peakInteg_01.log"
          ]
        }, 
        {
          "Path": [
            "140722_peakInteg_01.log"
          ]
        }
      ]
    }, 
    {
      "TimeEpoch": "Mac", 
      "TimeOffset": 0.0, 
      "FirstImageCorrelation": false, 
      "ZeroImageCorrelation": false, 
      "Name": "Dlogger", 
      "Files": [
        {
          "Path": [
            "140721_datalogger_01.log"
          ]
        }, 
        {
          "Path": [
            "140722_datalogger_01.log"
          ]
        }
      ]
    }
  ], 

  "OutputFormats": {
    "csv": true, 
    "hdf": true, 
    "exel": true, 
    "json": true
  }, 
  "OutputFileBaseName": "../result/merged", 
  "HDFOptions": {
    "IncludeCHI": true, 
    "IncludeTIF": false
  }
}
